# Generated by Django 6.0.4 on 2026-04-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dette',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='revenu',
            name='description',
        ),
        migrations.AddField(
            model_name='depense',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dette',
            name='categorie',
            field=models.CharField(default='Divers', max_length=100),
        ),
        migrations.AddField(
            model_name='dette',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='revenu',
            name='categorie',
            field=models.CharField(default='Divers', max_length=100),
        ),
        migrations.AddField(
            model_name='revenu',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(default='Divers', max_length=100),
        ),
    ]
