# Generated by Django 6.0.4 on 2026-04-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_depense_description_remove_dette_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dette',
            name='nom_personne',
        ),
    ]
